### ISSUE TITLE
Learning bugs

### ISSUE THREAD

**Issue by ProfNagorski** [HalcyonDays11/DiscordRPBot#5]
So far, three separate instances of a bug (or bugs?) associated with the !learn command. I cannot figure out how to reproduce them.

1. Student ended up with unlimited fails when learning a spell. Best guess is that the bot wasn't writing the fails to the DB?
2. Student failed once when learning a spell, then was told they didn't have any more attempts that day. Basically the complete opposite of what happened to the other student.
3. Successful Learns were not logged in the spellbook. Had several students learn a spell, succeed, but their spellbook didn't record the new modifier, even though they were no longer allowed to learn for the day. 

These all feel like some issue writing to the DB, but I don't know squat about Java DBs so I'm not sure...

**Comment by ProfNagorski** [comment]
These are becoming regular occurrences... I still can't reproduce it on purpose. I've asked around, and so far we can't find a trigger. Is there any way to prioritize these bug thingies? *cries*

**Comment by HalcyonDays11** [comment]
Okay, so I think this is fixed now.  We can reopen if not.
