### ISSUE TITLE
Modify Spellbook with a Boost

### ISSUE THREAD

**Issue by ProfNagorski** [HalcyonDays11/DiscordRPBot#6]
You can modify a spellbook to be 1 point higher than you can learn a spell. So, take Lumos, DC 2. I can learn until I have a +1 modifier, then I get the message that I've mastered the spell, as I should. But if I modify my spellbook, I can have up to a +2 modifier. To be completely honest, I like this bug. So I don't know what's doing it, but I'd rather not get rid of it? Because we can use "Boosted Spells" as a reward, and then you can master a spell even when burdened. But it's probably a good idea to figure out why it's doing that so that we can make it a permanent thing, or so that we can make a note to not fix it even if it looks wrong? Especially since this is a new development.

**Comment by KatherinePapcun** [comment]
So, in looking at the ModifySpellbookCommand, it doesn't seem to me that we're doing any validation at all that the values you want to modify it to are actually sane.    I think you could use this command to set the value to -1 or a million if you wanted to.  Garbage in, garbage out.  :)

We can add some warnings that tell you if you're about to do something truly crazy, or prevent you from doing something crazy.   But we could still allow you to still do some stuff like your example, where the prof wants to set it to something that's technically outside the normal rules but still mostly reasonable.

**Comment by HalcyonDays11** [comment]
So, I don't think there's anything to do with this task.  Seems like it's working as intended, and requires no changes.
